version: '3'

services:
  backup-keewee:
    image: debian:10
    command: tar cvf /backup/keewee_backup.tar /share
    volumes:
      - backup:/backup
      - keewee_dav-share:/share:ro
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.platform.os == linux
          - node.labels.webdav.data == true

  backup-edmm:
    image: mariadb
    command: bash -c "
      mkdir -p /backup/edmm &&
      mariabackup --backup --compress --target-dir=/backup/edmm --host=db --user=root --password=${EDMM_PASSWORD} &&
      tar cfvz /backup/edmm_backup.tgz /backup/edmm &&
      rm -rf /backup/edmm
      "
    networks:
      - edmm_edmm
    volumes:
      - backup:/backup
      - edmm_dbdata:/var/lib/mysql:ro
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.platform.os == linux


networks:
  edmm_edmm:
    external: true

volumes:
  backup:
    
  keewee_dav-share:
    external: true
    
  edmm_dbdata:
    external: true
