version: '3.9'

services:
  metabase:
    image: metabase/metabase:v0.37.0.2
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MGID: "${GID-1000}"
    volumes:
      - /var/lib/crowdsec/data:/metabase-data/
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.crowdsec.metabase == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.metabase-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.metabase-https.entrypoints=https
        - traefik.http.routers.metabase-https.tls=true
        - traefik.http.routers.metabase-https.tls.certresolver=le
        - traefik.http.services.metabase.loadbalancer.server.port=3000

networks:
  traefik-public:
    external: true
